// <auto-generated />
using System;
using InsightStream.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InsightStream.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InsightStreamDbContext))]
    [Migration("20260725172104_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InsightStream.Core.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomDomain")
                        .HasColumnType("text")
                        .HasColumnName("custom_domain");

                    b.Property<string>("MediumHandle")
                        .HasColumnType("text")
                        .HasColumnName("medium_handle");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_authors");

                    b.HasIndex("CustomDomain")
                        .IsUnique()
                        .HasDatabaseName("ix_authors_custom_domain");

                    b.HasIndex("MediumHandle")
                        .IsUnique()
                        .HasDatabaseName("ix_authors_medium_handle");

                    b.ToTable("authors", (string)null);
                });

            modelBuilder.Entity("InsightStream.Core.Entities.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<decimal>("PriorityScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(5.00m)
                        .HasColumnName("priority_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<string>("UrlHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("url_hash");

                    b.HasKey("Id")
                        .HasName("pk_links");

                    b.HasIndex("PriorityScore")
                        .IsDescending()
                        .HasDatabaseName("ix_links_priority_score");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_links_status");

                    b.HasIndex("UrlHash")
                        .IsUnique()
                        .HasDatabaseName("ix_links_url_hash");

                    b.ToTable("links", (string)null);
                });

            modelBuilder.Entity("InsightStream.Core.Entities.LinkAuthor", b =>
                {
                    b.Property<Guid>("LinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("link_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("LinkId", "AuthorId")
                        .HasName("pk_link_authors");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_link_authors_author_id");

                    b.ToTable("link_authors", (string)null);
                });

            modelBuilder.Entity("InsightStream.Core.Entities.Newsletter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DestinationEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination_email");

                    b.Property<string>("EmailHash")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("email_hash");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_content");

                    b.Property<DateTimeOffset>("ReceivedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_newsletters");

                    b.HasIndex("EmailHash")
                        .IsUnique()
                        .HasDatabaseName("ix_newsletters_email_hash");

                    b.ToTable("newsletters", (string)null);
                });

            modelBuilder.Entity("InsightStream.Core.Entities.NewsletterLink", b =>
                {
                    b.Property<Guid>("NewsletterId")
                        .HasColumnType("uuid")
                        .HasColumnName("newsletter_id");

                    b.Property<Guid>("LinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("link_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("NewsletterId", "LinkId")
                        .HasName("pk_newsletter_links");

                    b.HasIndex("LinkId")
                        .HasDatabaseName("ix_newsletter_links_link_id");

                    b.ToTable("newsletter_links", (string)null);
                });

            modelBuilder.Entity("InsightStream.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-7000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PasswordHash = "$2a$11$Lemo1jqJeszZ7t4DtrQe3.KDbMT67aBQa9adkEDaLH7im39QgUMuq",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("InsightStream.Core.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PreferenceType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("preference_type");

                    b.Property<string>("PreferenceValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preference_value");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_user_preferences");

                    b.HasIndex("UserId", "PreferenceType", "PreferenceValue")
                        .IsUnique()
                        .HasDatabaseName("ix_user_preferences_user_id_preference_type_preference_value");

                    b.ToTable("user_preferences", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_preferences_weight_range", "weight >= -1.00 AND weight <= 1.00");
                        });
                });

            modelBuilder.Entity("InsightStream.Core.Entities.LinkAuthor", b =>
                {
                    b.HasOne("InsightStream.Core.Entities.Author", "Author")
                        .WithMany("LinkAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_link_authors_authors_author_id");

                    b.HasOne("InsightStream.Core.Entities.Link", "Link")
                        .WithMany("LinkAuthors")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_link_authors_links_link_id");

                    b.Navigation("Author");

                    b.Navigation("Link");
                });

            modelBuilder.Entity("InsightStream.Core.Entities.NewsletterLink", b =>
                {
                    b.HasOne("InsightStream.Core.Entities.Link", "Link")
                        .WithMany("NewsletterLinks")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_newsletter_links_links_link_id");

                    b.HasOne("InsightStream.Core.Entities.Newsletter", "Newsletter")
                        .WithMany("NewsletterLinks")
                        .HasForeignKey("NewsletterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_newsletter_links_newsletters_newsletter_id");

                    b.Navigation("Link");

                    b.Navigation("Newsletter");
                });

            modelBuilder.Entity("InsightStream.Core.Entities.UserPreference", b =>
                {
                    b.HasOne("InsightStream.Core.Entities.User", "User")
                        .WithMany("UserPreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_preferences_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsightStream.Core.Entities.Author", b =>
                {
                    b.Navigation("LinkAuthors");
                });

            modelBuilder.Entity("InsightStream.Core.Entities.Link", b =>
                {
                    b.Navigation("LinkAuthors");

                    b.Navigation("NewsletterLinks");
                });

            modelBuilder.Entity("InsightStream.Core.Entities.Newsletter", b =>
                {
                    b.Navigation("NewsletterLinks");
                });

            modelBuilder.Entity("InsightStream.Core.Entities.User", b =>
                {
                    b.Navigation("UserPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
